# Generated by Django 3.1.3 on 2022-06-17 21:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=200)),
                ('hood_location', models.CharField(max_length=200)),
                ('hood_description', models.TextField(blank=True, max_length=500)),
                ('hood_photo', cloudinary.models.CloudinaryField(default='photo', max_length=255, verbose_name='photo')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
